name: Docker Image CI

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: ./
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag face-recognition:latest
    - name: Tag Docker Image
      run: docker tag face-recognition:latest kz16/face-recognition:latest
    - name: Push the Docker image
      run: docker push kz16/face-recognition:latest
